# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-13 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ndi_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['title'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
