# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-20 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ndi_app', '0004_activity_worksinactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=10, verbose_name='Номер')),
                ('d_path', models.TextField()),
                ('point_path', models.TextField()),
                ('activity', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='number_for_activity', to='ndi_app.Activity', verbose_name='Деятельность')),
            ],
        ),
    ]
