# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-20 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ndi_app', '0005_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='number',
            name='activity',
        ),
        migrations.AddField(
            model_name='activity',
            name='number',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='number', to='ndi_app.Number', verbose_name='Номер'),
            preserve_default=False,
        ),
    ]
