# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-20 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndi_app', '0006_auto_20180820_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250, verbose_name='Название слайда')),
                ('image', models.ImageField(upload_to='images/mainslide/', verbose_name='фото')),
            ],
        ),
        migrations.RenameField(
            model_name='photos_for_portfolio',
            old_name='photo',
            new_name='design',
        ),
    ]
