# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-29 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ndi_app', '0007_auto_20180820_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250, verbose_name='Название файла')),
                ('file', models.FileField(upload_to='', verbose_name='Файл')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_for_activity', to='ndi_app.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesOfExpertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=500, verbose_name='Название вида экспертизы')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_of_activity', to='ndi_app.Activity')),
            ],
        ),
    ]
