# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-29 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndi_app', '0008_downloadfiles_servicesofexpertise'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expertise',
            options={'ordering': ['name'], 'verbose_name': 'экспертиза', 'verbose_name_plural': 'Экспертиза'},
        ),
        migrations.RemoveField(
            model_name='downloadfiles',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='expertise',
            name='file',
        ),
        migrations.RemoveField(
            model_name='servicesofexpertise',
            name='activity',
        ),
        migrations.AddField(
            model_name='expertise',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/expertise/', verbose_name='фото для экспертизы'),
        ),
        migrations.AddField(
            model_name='expertise',
            name='text',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expertise',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Название'),
        ),
    ]
