# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-29 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ndi_app', '0009_auto_20180829_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadfiles',
            name='expertise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_for_expertise', to='ndi_app.Expertise', verbose_name='Файл для экспертизы'),
        ),
        migrations.AddField(
            model_name='servicesofexpertise',
            name='expertise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_of_expertise', to='ndi_app.Expertise', verbose_name='Услуга для экспертизы'),
        ),
    ]
