# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-06 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndi_app', '0011_auto_20180829_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksinactivity',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True, verbose_name='Название'),
        ),
    ]
