# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-13 10:28
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ndi_app', '0012_auto_20180906_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksinactivity',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
    ]
